#!/bin/sh
set -eu

publication_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
repository_dir=$(git -C "$publication_dir" rev-parse --show-toplevel)
output_file="$publication_dir/handbook/generated/build_metadata.tex"

source_revision=$(git -C "$repository_dir" rev-parse --short=12 HEAD)
generation_date=$(date -u '+%Y-%m-%d %H:%M UTC')

if [ -n "$(git -C "$repository_dir" status --porcelain --untracked-files=normal)" ]; then
    worktree_state="Dirty preview"
    worktree_notice="Source tree contains uncommitted changes"
else
    worktree_state="Clean"
    worktree_notice="Source tree was clean at build time"
fi

mkdir -p "$(dirname -- "$output_file")"
mkdir -p \
    "$publication_dir/build/handbook/frontmatter" \
    "$publication_dir/build/handbook/chapters" \
    "$publication_dir/build/handbook/appendices"
printf '%s\n' \
    '% Generated by scripts/generate_build_metadata.sh. Do not edit.' \
    "\\newcommand{\\HandbookSourceRevision}{$source_revision}" \
    "\\newcommand{\\NOIRLabGenerationDate}{$generation_date}" \
    "\\newcommand{\\HandbookWorktreeState}{$worktree_state}" \
    "\\newcommand{\\HandbookWorktreeNotice}{$worktree_notice}" \
    > "$output_file"
